### ISSUE TITLE
Minions?

### ISSUE THREAD

**Issue by TopoR1** [Yuu6883/OgarX#5]
Hey! Could you make minions on this server?

**Comment by Yuu6883** [comment]
Not with the current engine, since it only supports 250 "players" (stored in a byte per cell) meaning if a lot of minions are added they will just take the player spots and nobody will be able to join.

**Comment by Yuu6883** [comment]
Unless minions are implemented with a separate type or treated as pellets and kept in an array for the player, and having their positions updated according to the player's mouse position, but then they won't be able to split/eat anything.

**Comment by TopoR1** [comment]
I think it's better to put them in the player array (inherit from the player) to make it easier to interact with them ... but this can have a big performance impact ... I'll be thinking about how this can be implemented, but for now there is a separate proposal from the player to store minions in an array and interact with the owner (player) by id

**Comment by Yuu6883** [comment]
A simple solution could be just changing the cell type to unsigned short (65536 possible values) then we don't need to worry about running out of ids. But not sure what impact it will have on the engine since the cell struct size will change and all the getters in the cell class will be reading from the wrong offset.
